---

- name: install key
  apt_key:
    url: "{{ sensu_apt_key_url }}"
    state: present
  register: sensu_key_installed

- name: add repos
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: no
  with_items: "{{ sensu_apt_repositories }}"
  when: sensu_key_installed|success
  register: sensu_repo_installed

- name: update apt cache
  apt:
    update_cache: yes
  when: sensu_repo_installed|changed

- name: install apt packages
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
    update_cache: yes
    cache_valid_time: 86400
  with_items: "{{ sensu_packages }}"
  when: sensu_repo_installed|success

- name: add sensu user to admin group
  user:
    name: sensu
    groups: "{{ admin_user_group }}"
    append: yes
  when: admin_user_group is defined

- name: config
  template:
    src: sensu.json.j2
    dest: "/etc/sensu/conf.d/{{ item }}.json"
  with_items: "{{ sensu_config }}"
  notify:
    - restart sensu server
    - restart sensu api
    - restart sensu client
  tags: sensu_config

- name: install plugins
  gem:
    name: "sensu-plugins-{{ item }}"
    state: present
    executable: /opt/sensu/embedded/bin/gem
    user_install: no
  with_items: "{{ sensu_plugins }}"
  when: sensu_plugins | length() > 0

- name: server > service start
  service:
    name: "{{ sensu_server_daemon }}"
    state: started
    enabled: yes
  when: sensu_server_daemon_enabled

- name: api > service start
  service:
    name: "{{ sensu_api_daemon }}"
    state: started
    enabled: yes
  when: sensu_api_daemon_enabled

- name: client > service start
  service:
    name: "{{ sensu_client_daemon }}"
    state: started
    enabled: yes
  when: sensu_client_daemon_enabled

- include: uchiwa.yml
  when: sensu_uchiwa_enabled
