---

- name: restart sensu server
  service:
    name: "{{ sensu_server_daemon }}"
    state: restarted
  when: sensu_server_daemon_enabled

- name: restart sensu api
  service:
    name: "{{ sensu_api_daemon }}"
    state: restarted
  when: sensu_api_daemon_enabled

- name: restart sensu client
  service:
    name: "{{ sensu_client_daemon }}"
    state: restarted
  when: sensu_client_daemon_enabled

- name: restart uchiwa
  service:
    name: "{{ sensu_uchiwa_daemon }}"
    state: restarted
  when: sensu_uchiwa_enabled
